In [6]:
import numpy as np
mylist = [1,2,3]
type(mylist)

list

In [7]:
np.array(mylist)


array([1, 2, 3])

In [8]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
mymatrix = np.array(mylist)

In [10]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mymatrix.shape

(3, 3)

In [12]:
# start at start, go up to but not including stop in increments of 2
# create an array of numbers starting at 0, going up to but not including 11 in steps of 2
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# np.zeros accepts a single number of a tuple (r,c)
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# operations can be broadcast to all the elements in the array/matrix unlike normal lists
np.ones((3,3)) + 5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [17]:
np.ones(5) / 100

array([0.01, 0.01, 0.01, 0.01, 0.01])

In [23]:
# we can create linearly spaced numbers over a specified interval
# inclusive start and stop, and we tell it please give me x numbers between the start and stop
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# gives you a random number(s) from a `uniform distribution` between 0 and 1
# uniform distrib -> every number between 0 and 1 has an equal chance of being chosen
np.random.rand(1)

array([0.07709119])

In [24]:
np.random.rand(5,5)

array([[0.58120733, 0.14267862, 0.94591918, 0.33999059, 0.62043546],
       [0.45295964, 0.23976742, 0.03450459, 0.14859311, 0.81086617],
       [0.65310538, 0.54446869, 0.04119477, 0.46816625, 0.88874673],
       [0.47625856, 0.41248898, 0.61610654, 0.32141655, 0.58086926],
       [0.39661405, 0.02009137, 0.4313959 , 0.41124451, 0.62906175]])

In [25]:
# can also get random numbers from a standard normal distribution
# mean of 0, sd of 1
np.random.randn(3,2)

array([[-1.25202366,  0.00934516],
       [-0.85378886,  0.39068831],
       [-0.49267415, -0.5824889 ]])

In [21]:
# Also one for random integers
# Here I want 10 random integers between 1 - 100, where 100 is not included
np.random.randint(1,100,10)

array([93, 50, 20, 35, 47, 41, 84,  3, 93, 27])

In [22]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [26]:
arr = np.arange(25)

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([26, 17, 48, 32,  8, 48, 48, 42, 12, 41])

In [31]:
ranarr.min()

8

In [32]:
ranarr.max()

48

In [33]:
# index of max number?
ranarr.argmax()

2

In [34]:
ranarr.argmin()

4

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[8]

8

In [38]:
# like list slicing - start, to stop but not including stop
arr[1:5]

array([1, 2, 3, 4])

In [39]:
# Broadcasting
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [40]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [41]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [42]:
# If I take a copy of an array and change it, it changes the original array (pointing to orig arr)
# need to keep that in mind - if you don't want to affect the original array you need to
# do an explicit copy
slice_arr = arr[0:6]
slice_arr[:] = 99
print(f'slice_arr is {slice_arr}, while arr is {arr}. Whoa, look at that we affected the original array')

slice_arr is [99 99 99 99 99 99], while arr is [99 99 99 99 99 99  6  7  8  9 10]. Whoa, look at that we affected the original array


In [43]:
arr_cp = arr.copy()

In [44]:
arr_cp[:] = 100
arr_cp

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [46]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [47]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d.shape

(3, 3)

In [49]:
arr_2d[1] # returns row at index 1

array([20, 25, 30])

In [50]:
arr_2d[1,1]

25

In [51]:
arr_2d[2,2]

45

In [52]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [53]:
# conditional selection
arr = np.arange(1,11)

In [54]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
bool_arr = arr > 4

In [56]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[arr > 4] # one step

array([ 5,  6,  7,  8,  9, 10])

In [58]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [59]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [60]:
arr.sum()

55

In [61]:
arr.max()

10

In [65]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
arr_2d.shape

(3, 4)

In [67]:
arr_2d.sum()

78

In [68]:
arr_2d.sum(axis = 0) # give me the sum across the rows, which is essentially the sum of the columns

array([15, 18, 21, 24])

In [69]:
arr_2d.sum(axis = 1) # across the cols == sum of the rows

array([10, 26, 42])